In [1]:
from roboflow import Roboflow
rf = Roboflow(api_key="XVGnocCYSPQRy7DmLzqu")
project = rf.workspace("trail-5cssd").project("nigga-2nvhi")
version = project.version(3)
dataset = version.download("yolov12")
                

loading Roboflow workspace...
loading Roboflow project...



Extracting Dataset Version Zip to nigga-3 in yolov12:: 100%|█| 530/530 [00:00<00


In [2]:
from ultralytics import YOLO
from IPython.display import Image

In [3]:
dataset.location

'/home/tik/Desktop/people/nigga-3'

In [4]:
!yolo task=detect mode=train data={dataset.location}/data.yaml model="yolo12n.pt" epochs=100 imgsz=640

100%|██████████████████████████████████████| 5.34M/5.34M [00:00<00:00, 8.70MB/s]
New https://pypi.org/project/ultralytics/8.3.161 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.159 🚀 Python-3.12.2 torch-2.6.0+cu124 CPU (12th Gen Intel Core(TM) i5-12400F)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/tik/Desktop/people/nigga-3/data.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo12n.p

In [ ]:
import cv2
import numpy as np
from ultralytics import YOLO

# Load the trained YOLOv11 model
model = YOLO("runs/detect/train/weights/best.pt")  # Path to your trained model weights

def detect_objects(frame):
    results = model(frame)
    detected_objects = []

    for r in results:
        for box in r.boxes:
            class_id = int(box.cls[0])  # Get class ID
            confidence = box.conf[0].item()  # Confidence score

            if confidence > 0.7:
                label = model.names[class_id]
                detected_objects.append(label)

                # Draw bounding box
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
                cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

    return frame, detected_objects


def main():
    cap = cv2.VideoCapture(0)  # Open webcam

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame, detected_objects = detect_objects(frame)
        cv2.imshow("yolo", frame)
        if detected_objects:
            print(detected_objects,frame)  #
        key = cv2.waitKey(1) & 0xFF

    cap.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()


0: 480x640 (no detections), 42.0ms
Speed: 2.1ms preprocess, 42.0ms inference, 0.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 people, 48.8ms
Speed: 1.7ms preprocess, 48.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 2 peoples, 52.5ms
Speed: 1.8ms preprocess, 52.5ms inference, 0.8ms postprocess per image at shape (1, 3, 480, 640)
['people'] [[[143 145 133]
  [142 143 132]
  [140 144 132]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[143 145 133]
  [143 145 133]
  [141 145 133]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[143 145 133]
  [143 145 133]
  [140 144 132]
  ...
  [ 71  71  71]
  [  0 255   0]
  [  0 255   0]]

 ...

 [[197 196 213]
  [197 196 213]
  [196 195 211]
  ...
  [ 39  64  66]
  [ 42  62  68]
  [ 39  60  66]]

 [[197 195 216]
  [196 194 215]
  [195 193 212]
  ...
  [ 32  63  67]
  [ 39  63  68]
  [ 38  62  67]]

 [[198 193 215]
  [196 191 212]
  [195 191 209]
  ...
  [ 31  62  66]
  [ 38 

0: 480x640 1 people, 52.6ms
Speed: 2.8ms preprocess, 52.6ms inference, 0.5ms postprocess per image at shape (1, 3, 480, 640)
['people'] [[[142 144 137]
  [142 144 137]
  [142 144 137]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[143 146 137]
  [142 145 136]
  [142 145 136]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[143 146 138]
  [142 144 137]
  [142 144 137]
  ...
  [ 36  40  40]
  [ 42  42  42]
  [  0 255   0]]

 ...

 [[134 134 122]
  [127 127 115]
  [129 121 104]
  ...
  [ 42  62  64]
  [ 45  64  68]
  [ 45  64  68]]

 [[138 133 122]
  [133 127 117]
  [129 120 105]
  ...
  [ 44  64  65]
  [ 46  63  65]
  [ 46  63  65]]

 [[138 133 122]
  [131 126 115]
  [128 120 110]
  ...
  [ 42  63  66]
  [ 39  64  66]
  [ 39  64  66]]]

0: 480x640 1 people, 53.4ms
Speed: 1.1ms preprocess, 53.4ms inference, 0.9ms postprocess per image at shape (1, 3, 480, 640)
['people'] [[[141 143 136]
  [141 143 136]
  [142 146 134]
  ...
  [  0 255   0]
  [  0 255   0]
  [  0 255 

# 

In [3]:
from ultralytics import YOLO
import cv2
import math 
import serial
import time
# start webcam
cap = cv2.VideoCapture(0)
cap.set(3, 1280)
cap.set(4, 720)
arduinoData = serial.Serial("/dev/ttyACM0", 115200)

def send_coordinates_to_arduino(x, y):
    # Convert the coordinates to a string and send it to Arduino
    coordinates = f"{x},{y}\r"
    #signal = "true"
    #arduinoData.write(signal.encode())
    arduinoData.write(coordinates.encode())
    print(f"X{x}Y{y}\n")


# model
model = YOLO("runs/detect/train/weights/best.pt") 
# object classes
classNames = ["person"]


while True:
    success, img = cap.read()
    results = model(img, stream=True)

    # coordinates
    for r in results:
        boxes = r.boxes

        for box in boxes:
            # bounding box
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2) # convert to int values

            # put box in cam
            cv2.rectangle(img, (x1, y1), (x2, y2), (255, 0, 255), 3)

            # class name
            cls = int(box.cls[0])
            classname = classNames[cls]
            
            # object details
            org = [x1, y1]
            font = cv2.FONT_HERSHEY_SIMPLEX
            fontScale = 1
            color = (255, 255, 255)
            thickness = 1
            if classname == "person":
                if abs(x2 - x1) > 300:
                    x = (x1 + x2)/2
                    y = (y1 + y2)/2
                    #print("Class name -->", classNames[cls])
                    #print(x,y)
                    cv2.putText(img, classNames[cls], org, font, fontScale, color, thickness)
                    
                    signal = f" 12331 "  # send serial data
                    print(type(signal))
                 #   arduinoData.write(signal.encode())
                    send_coordinates_to_arduino(x, y)

    cv2.imshow("Webcam", img)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

SerialException: [Errno 16] could not open port /dev/ttyACM0: [Errno 16] Device or resource busy: '/dev/ttyACM0'

In [ ]:
import serial